### ISSUE TITLE
Decide on blake2b personalizations for transcript and parameter generation

### ISSUE THREAD

**Issue by ebfull** [zcash/halo2#182]

**Comment by daira** [comment]
For parameter generation, the definition of hash-to-curve in the draft Orchard spec doesn't use BLAKE2b personalization (or rather, it uses personalization of all-zeros). This is because it uses XMD:BLAKE2b from the Internet Draft, which is designed to work with arbitrary hash functions (and to accept domain separation tags of up to 255 characters, which BLAKE2b personalization wouldn't support). I think following the I-D is preferable here.

**Comment by daira** [comment]
To document what is implemented in #204:
* the domain separation prefix is "Halo2-Parameters";
* the message for G<sub>i</sub> is [0] || I2LEOSP<sub>32</sub>(i), for 0 ≤ i < n;
* the message for H is [1];
* the message for U is [2].
