### ISSUE TITLE
MockProver.verify() panics 

### ISSUE THREAD

**Issue by themighty1** [zcash/halo2#684]
(Using halo2 main branch with the most recent changes) 
I made a trivial change to my circuit and MockProver.verify() now panics in my tests.

I made a repro branch with 2 top-level commits - before the last commit `cargo test test_circuit` succeeded. After a small change to the circuit `cargo test test_circuit` causes a panic from inside MockProver.verify() 
https://github.com/themighty1/tlsn/commits/mockprover_panic

The test which triggers the panic is located here:
https://github.com/themighty1/tlsn/blob/abdcbb98d7c66f61326ee8a755530eba4845b875/authdecode/src/halo2_backend/prover.rs#L239

The test feeds the wrong public inputs to the circuit and expects that verification fails, not panics.

**Comment by therealyingtong** [comment]
Thanks for identifying this edge case, I think it will require a change in how the `MockProver` handles regions with no area.

The panic is triggered by:
https://github.com/zcash/halo2/blob/ec9dcefe9103fc23c13e8195120419d4d2f232a6/halo2_proofs/src/dev/failure.rs#L90

and it's caused by the breaking commit introducing regions that do purely `constrain_equal` (i.e. don't assign anything and have no area).

```rust
layouter.assign_region(
    || "constrain output",
    |mut region| {
        region.constrain_equal(output.cell(), expected1.cell())?;
        Ok(())
    },
)?;
```

**Comment by therealyingtong** [comment]
This has to do with how the `MockProver` handles zero-area regions when finding the `FailureLocation`. The breaking commit introduced two such regions, in which no cells were assigned and only `constrain_equal()` was called. We should return `FailureLocation::OutsideRegion` instead of panicking (see https://github.com/zcash/halo2/pull/685).
